/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class edgeSegFrame extends javax.swing.JFrame {

    /**
     * Creates new form edgeSegFrame
     */
    public edgeSegFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edgepsrc = new javax.swing.JPanel();
        edgepdest = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edgerbe = new javax.swing.JRadioButton();
        edgerbd = new javax.swing.JRadioButton();
        edgeslider = new javax.swing.JSlider();
        bedgesave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Tfthresh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        edgepsrc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout edgepsrcLayout = new javax.swing.GroupLayout(edgepsrc);
        edgepsrc.setLayout(edgepsrcLayout);
        edgepsrcLayout.setHorizontalGroup(
            edgepsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        edgepsrcLayout.setVerticalGroup(
            edgepsrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        getContentPane().add(edgepsrc);
        edgepsrc.setBounds(80, 60, 320, 240);

        edgepdest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout edgepdestLayout = new javax.swing.GroupLayout(edgepdest);
        edgepdest.setLayout(edgepdestLayout);
        edgepdestLayout.setHorizontalGroup(
            edgepdestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        edgepdestLayout.setVerticalGroup(
            edgepdestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        getContentPane().add(edgepdest);
        edgepdest.setBounds(480, 60, 310, 240);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Threshold");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 350, 80, 16);

        edgerbe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        edgerbe.setText("Enable");
        getContentPane().add(edgerbe);
        edgerbe.setBounds(60, 380, 71, 27);

        edgerbd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        edgerbd.setText("Disable");
        getContentPane().add(edgerbd);
        edgerbd.setBounds(60, 410, 73, 27);

        edgeslider.setMajorTickSpacing(40);
        edgeslider.setMaximum(255);
        edgeslider.setMinorTickSpacing(10);
        edgeslider.setPaintLabels(true);
        edgeslider.setPaintTicks(true);
        edgeslider.setSnapToTicks(true);
        getContentPane().add(edgeslider);
        edgeslider.setBounds(220, 400, 450, 50);

        bedgesave.setText("Save");
        getContentPane().add(bedgesave);
        bedgesave.setBounds(710, 400, 61, 25);

        jLabel2.setText("Threshold");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(361, 360, 100, 16);

        Tfthresh.setEditable(false);
        getContentPane().add(Tfthresh);
        Tfthresh.setBounds(440, 360, 50, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edgeSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edgeSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edgeSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edgeSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edgeSegFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tfthresh;
    private javax.swing.JButton bedgesave;
    private javax.swing.JPanel edgepdest;
    private javax.swing.JPanel edgepsrc;
    private javax.swing.JRadioButton edgerbd;
    private javax.swing.JRadioButton edgerbe;
    private javax.swing.JSlider edgeslider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
