/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ssd
 */
public class watershedSegFrame extends javax.swing.JFrame {

    /**
     * Creates new form watershedSegFrame
     */
    public watershedSegFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jradioButton1 = new javax.swing.JRadioButton();
        jradiobutton2 = new javax.swing.JRadioButton();
        edgeslider = new javax.swing.JSlider();
        bedgesave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Tfthresh = new javax.swing.JTextField();
        edgesrc = new javax.swing.JLabel();
        edgedest = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Threshold");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 300, 80, 16);

        jradioButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jradioButton1.setText("Enable");
        jradioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jradioButton1);
        jradioButton1.setBounds(10, 330, 67, 27);

        jradiobutton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jradiobutton2.setText("Disable");
        jradiobutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jradiobutton2);
        jradiobutton2.setBounds(10, 360, 71, 27);

        edgeslider.setMajorTickSpacing(40);
        edgeslider.setMaximum(255);
        edgeslider.setMinorTickSpacing(10);
        edgeslider.setPaintLabels(true);
        edgeslider.setPaintTicks(true);
        edgeslider.setSnapToTicks(true);
        edgeslider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                edgesliderStateChanged(evt);
            }
        });
        getContentPane().add(edgeslider);
        edgeslider.setBounds(170, 350, 450, 50);

        bedgesave.setText("Save");
        bedgesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedgesaveActionPerformed(evt);
            }
        });
        getContentPane().add(bedgesave);
        bedgesave.setBounds(660, 350, 57, 23);

        jLabel2.setText("Flood Point Count");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 310, 100, 14);

        Tfthresh.setEditable(false);
        getContentPane().add(Tfthresh);
        Tfthresh.setBounds(420, 310, 50, 20);

        edgesrc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(edgesrc);
        edgesrc.setBounds(40, 40, 310, 190);

        edgedest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(edgedest);
        edgedest.setBounds(460, 40, 300, 190);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(180, 430, 430, 26);

        jLabel3.setText("Minimum Window Width");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 400, 120, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 400, 50, 20);

        jLabel4.setText("Connected Pixels");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 470, 90, 14);

        jRadioButton1.setText("4 Pixels");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(420, 470, 61, 23);

        jRadioButton2.setText("8 Pixels");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(520, 470, 61, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jradioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jradioButton1ActionPerformed

    private void jradiobutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobutton2ActionPerformed
        // TODO add your handling code here:
        thresholdActive=false;
        edgeslider.setEnabled(false);
    }//GEN-LAST:event_jradiobutton2ActionPerformed

    private void edgesliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_edgesliderStateChanged

        // TODO add your handling code here:
        JSlider source = (JSlider)evt.getSource();
        if (!source.getValueIsAdjusting()) {
            System.out.println("threshold="+source.getValue());
            threshold=source.getValue();
            Tfthresh.setText(""+source.getValue());
            processImage();

        }
    }//GEN-LAST:event_edgesliderStateChanged

    private void bedgesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedgesaveActionPerformed
        FileHandling fh=new FileHandling(this);
        fh.WriteImage(bimage);

    }//GEN-LAST:event_bedgesaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(watershedSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(watershedSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(watershedSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(watershedSegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new watershedSegFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tfthresh;
    private javax.swing.JButton bedgesave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel edgedest;
    private javax.swing.JSlider edgeslider;
    private javax.swing.JLabel edgesrc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jradioButton1;
    private javax.swing.JRadioButton jradiobutton2;
    // End of variables declaration//GEN-END:variables
}
